# Generated by Django 4.0.6 on 2022-12-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_remove_followrs_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followrs',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
