# Generated by Django 4.1.3 on 2022-12-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0009_alter_followrs_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followrs',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
