# Generated by Django 4.1.3 on 2022-12-05 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0010_alter_followrs_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followrs',
            name='phone',
        ),
    ]
