# Generated by Django 4.1.5 on 2023-01-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('username', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create time')),
            ],
        ),
    ]
