# Generated by Django 4.1.5 on 2023-02-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woow', '0003_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='month',
        ),
        migrations.AddField(
            model_name='post',
            name='url_name',
            field=models.URLField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
