# Generated by Django 4.1.5 on 2023-07-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woow', '0004_remove_post_month_post_url_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(default=None)),
            ],
        ),
    ]
