# Generated by Django 4.1.5 on 2024-03-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woow', '0006_delete_ipmodel_remove_post_address_post_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Kitob nomi:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='url_name',
            field=models.URLField(max_length=400, verbose_name='Kitob joylashgan sayt:'),
        ),
    ]
